const dataDisplayComponents = [
  {
    id: "data-table",
    name: "Data Table",
    slug: "data-table",
    category: "data-display",
    description: "Responsive striped table with hover states for displaying structured data.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["table", "data", "grid", "list"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "DataTable.jsx", path: "components/atoms/data-display/DataTable.jsx" }],
    uses: ["User lists", "Order history", "Analytics", "Admin panels"],
    pageId: "dataTable",
  },
  {
    id: "data-card",
    name: "Data Card",
    slug: "data-card",
    category: "data-display",
    description: "Metric card with value, trend indicator, icon and subtitle.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["card", "metric", "kpi", "dashboard"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "DataCard.jsx", path: "components/atoms/data-display/DataCard.jsx" }],
    uses: ["Dashboards", "KPI panels", "Analytics", "Stats overview"],
    pageId: "dataCard",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    slug: "skeleton",
    category: "data-display",
    description: "Shimmer placeholder shown while content is loading.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["skeleton", "loader", "placeholder", "shimmer"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Skeleton.jsx", path: "components/atoms/data-display/Skeleton.jsx" }],
    uses: ["Page loading", "Lazy images", "Feed loading", "API wait states"],
    pageId: "skeleton",
  },
  {
    id: "spinner",
    name: "Loaders & Spinners",
    slug: "spinner",
    category: "data-display",
    description: "Four loader variants — spinner, dots, pulse ring and bar loader.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["spinner", "loader", "loading", "animation"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Spinner.jsx", path: "components/atoms/data-display/Spinner.jsx" }],
    uses: ["Button loading", "Page transitions", "Data fetching", "Form submit"],
    pageId: "spinner",
  },
  {
    id: "progress-bar",
    name: "Progress Bar",
    slug: "progress-bar",
    category: "data-display",
    description: "Animated progress bar with label, value display and size variants.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["progress", "bar", "loading", "percentage"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "ProgressBar.jsx", path: "components/atoms/data-display/ProgressBar.jsx" }],
    uses: ["Upload progress", "Profile completion", "Skill levels", "Step indicators"],
    pageId: "progressBar",
  },
  {
    id: "empty-state",
    name: "Empty State",
    slug: "empty-state",
    category: "data-display",
    description: "Friendly empty state with icon, title, description and optional CTA.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["empty", "state", "placeholder", "cta"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "EmptyState.jsx", path: "components/atoms/data-display/EmptyState.jsx" }],
    uses: ["Empty lists", "No search results", "First-time users", "Error pages"],
    pageId: "emptyState",
  },
  {
    id: "tag",
    name: "Tag / Chip",
    slug: "tag",
    category: "data-display",
    description: "Soft or solid colored label chips with optional remove button.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["tag", "chip", "label", "badge"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Tag.jsx", path: "components/atoms/data-display/Tag.jsx" }],
    uses: ["Category labels", "Filter chips", "Skill tags", "Status badges"],
    pageId: "tag",
  },
  {
    id: "avatar-group",
    name: "Avatar Group",
    slug: "avatar-group",
    category: "data-display",
    description: "Stacked avatar group with overflow count for team displays.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["avatar", "group", "team", "users"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "AvatarGroup.jsx", path: "components/atoms/data-display/AvatarGroup.jsx" }],
    uses: ["Team members", "Collaborators", "Assignees", "Participants"],
    pageId: "avatarGroup",
  },
  {
    id: "timeline",
    name: "Timeline",
    slug: "timeline",
    category: "data-display",
    description: "Vertical timeline for activity feeds, changelogs and event history.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["timeline", "feed", "activity", "history"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Timeline.jsx", path: "components/atoms/data-display/Timeline.jsx" }],
    uses: ["Activity feed", "Changelog", "Order tracking", "Project milestones"],
    pageId: "timeline",
  },
  {
    id: "misc",
    name: "Misc Utilities",
    slug: "misc",
    category: "data-display",
    description: "Keyboard shortcut badge, section divider and hover tooltip.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["kbd", "divider", "tooltip", "utility"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Misc.jsx", path: "components/atoms/data-display/Misc.jsx" }],
    uses: ["Keyboard shortcuts", "Section separators", "Help tooltips", "UI polish"],
    pageId: "misc",
  },
];

export default dataDisplayComponents;
