const notificationComponents = [
  {
    id: "toast",
    name: "Toast",
    slug: "toast",
    category: "notifications",
    description: "Lightweight pop-up messages for success, error, warning and info feedback.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["toast", "notification", "feedback", "popup"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Toast.jsx", path: "components/atoms/notifications/Toast.jsx" }],
    uses: ["Form submission", "API responses", "Copy to clipboard", "Delete confirmation"],
    pageId: "toast",
  },
  {
    id: "alert",
    name: "Alert",
    slug: "alert",
    category: "notifications",
    description: "Inline alert banners with icon, title, message and optional dismiss button.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["alert", "notification", "banner", "inline"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Alert.jsx", path: "components/atoms/notifications/Alert.jsx" }],
    uses: ["Form validation", "Page-level warnings", "Feature announcements", "Error pages"],
    pageId: "alert",
  },
  {
    id: "banner",
    name: "Banner",
    slug: "banner",
    category: "notifications",
    description: "Full-width announcement banners with action button and dismiss.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["banner", "announcement", "notification", "full-width"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Banner.jsx", path: "components/atoms/notifications/Banner.jsx" }],
    uses: ["Cookie consent", "Maintenance notice", "Promotions", "System alerts"],
    pageId: "banner",
  },
  {
    id: "snackbar",
    name: "Snackbar",
    slug: "snackbar",
    category: "notifications",
    description: "Dark bottom notification with optional undo/action button.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["snackbar", "notification", "bottom", "action"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Snackbar.jsx", path: "components/atoms/notifications/Snackbar.jsx" }],
    uses: ["Undo actions", "Quick feedback", "File saved", "Item deleted"],
    pageId: "snackbar",
  },
  {
    id: "notification-card",
    name: "Notification Card",
    slug: "notification-card",
    category: "notifications",
    description: "Rich notification item with avatar, title, message, timestamp and unread state.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["notification", "card", "feed", "inbox"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "NotificationCard.jsx", path: "components/atoms/notifications/NotificationCard.jsx" }],
    uses: ["Notification center", "Activity feed", "Inbox", "Alerts panel"],
    pageId: "notificationCard",
  },
  {
    id: "notification-badge",
    name: "Notification Badge",
    slug: "notification-badge",
    category: "notifications",
    description: "Count or dot badge overlaid on any element like icons or avatars.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["badge", "count", "notification", "overlay"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "NotificationBadge.jsx", path: "components/atoms/notifications/NotificationBadge.jsx" }],
    uses: ["Nav icons", "Cart count", "Message count", "Alert indicators"],
    pageId: "notificationBadge",
  },
  {
    id: "status-dot",
    name: "Status Dot",
    slug: "status-dot",
    category: "notifications",
    description: "Presence indicator showing online, offline, busy, away or pending states.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["status", "presence", "dot", "indicator"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "StatusDot.jsx", path: "components/atoms/notifications/StatusDot.jsx" }],
    uses: ["User presence", "Service status", "Live indicators", "Chat apps"],
    pageId: "statusDot",
  },
  {
    id: "progress-notification",
    name: "Progress Notification",
    slug: "progress-notification",
    category: "notifications",
    description: "Upload or task progress displayed inside a notification card.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["progress", "notification", "upload", "task"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "ProgressNotification.jsx", path: "components/atoms/notifications/ProgressNotification.jsx" }],
    uses: ["File upload", "Export progress", "Background tasks", "Sync status"],
    pageId: "progressNotification",
  },
  {
    id: "confirm-dialog",
    name: "Confirm Dialog",
    slug: "confirm-dialog",
    category: "notifications",
    description: "Danger / warning confirmation modal with cancel and confirm actions.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["dialog", "modal", "confirm", "danger"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "ConfirmDialog.jsx", path: "components/atoms/notifications/ConfirmDialog.jsx" }],
    uses: ["Delete confirmation", "Destructive actions", "Logout", "Reset data"],
    pageId: "confirmDialog",
  },
  {
    id: "inline-message",
    name: "Inline Message",
    slug: "inline-message",
    category: "notifications",
    description: "Compact inline status message with icon for form fields or inline feedback.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["inline", "message", "status", "feedback"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "InlineMessage.jsx", path: "components/atoms/notifications/InlineMessage.jsx" }],
    uses: ["Field validation", "Inline hints", "Status labels", "Compact feedback"],
    pageId: "inlineMessage",
  },
];

export default notificationComponents;
