/**
 * Forms category registry
 * Each entry follows the same contract as buttons registry.
 * `component` and `previewProps` are omitted here because form components
 * have interactive state — FormDetails.jsx handles their live previews directly.
 */

const formComponents = [
  {
    id: "text-input",
    name: "Text Input",
    slug: "text-input",
    category: "forms",
    description: "Standard text input with icon prefix and error state support.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["input", "form", "text", "field"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "TextInput.jsx", path: "components/atoms/forms/TextInput.jsx" }],
    uses: ["User information", "Search fields", "Form data entry", "Text collection"],
    pageId: "textInput",
  },
  {
    id: "password-input",
    name: "Password Input",
    slug: "password-input",
    category: "forms",
    description: "Password field with show/hide toggle for better UX.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["input", "form", "password", "security"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "PasswordInput.jsx", path: "components/atoms/forms/PasswordInput.jsx" }],
    uses: ["Login forms", "Registration", "Password change", "Secure fields"],
    pageId: "passwordInput",
  },
  {
    id: "textarea",
    name: "Textarea",
    slug: "textarea",
    category: "forms",
    description: "Multi-line text input for longer content with resizable height.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["input", "form", "textarea", "multiline"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Textarea.jsx", path: "components/atoms/forms/Textarea.jsx" }],
    uses: ["Comments", "Descriptions", "Messages", "Long-form content"],
    pageId: "textarea",
  },
  {
    id: "search-input",
    name: "Search Input",
    slug: "search-input",
    category: "forms",
    description: "Search field with built-in search icon and onSearch callback.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["input", "form", "search", "filter"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "SearchInput.jsx", path: "components/atoms/forms/SearchInput.jsx" }],
    uses: ["Site search", "Filter lists", "Data lookup", "Navigation"],
    pageId: "searchInput",
  },
  {
    id: "select-dropdown",
    name: "Select Dropdown",
    slug: "select-dropdown",
    category: "forms",
    description: "Custom styled dropdown with options list and error support.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["select", "dropdown", "form", "choice"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "SelectDropdown.jsx", path: "components/atoms/forms/SelectDropdown.jsx" }],
    uses: ["Category selection", "Country picker", "Role assignment", "Filters"],
    pageId: "selectDropdown",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    slug: "checkbox",
    category: "forms",
    description: "Custom styled checkbox with label and checked state.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["checkbox", "form", "choice", "boolean"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "Checkbox.jsx", path: "components/atoms/forms/Checkbox.jsx" }],
    uses: ["Agreements", "Multi-select", "Preferences", "Feature flags"],
    pageId: "checkbox",
  },
  {
    id: "radio-button",
    name: "Radio Button",
    slug: "radio-button",
    category: "forms",
    description: "Custom radio button for single selection from a group.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["radio", "form", "choice", "selection"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "RadioButton.jsx", path: "components/atoms/forms/RadioButton.jsx" }],
    uses: ["Single choice", "Plan selection", "Gender field", "Preference"],
    pageId: "radioButton",
  },
  {
    id: "switch-toggle",
    name: "Switch Toggle",
    slug: "switch-toggle",
    category: "forms",
    description: "Toggle switch for binary on/off states with smooth animation.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["toggle", "switch", "form", "boolean"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "SwitchToggle.jsx", path: "components/atoms/forms/SwitchToggle.jsx" }],
    uses: ["Settings", "Feature toggles", "Preferences", "Enable/Disable"],
    pageId: "switchToggle",
  },
  {
    id: "range-slider",
    name: "Range Slider",
    slug: "range-slider",
    category: "forms",
    description: "Slider input for selecting a numeric value within a range.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["slider", "range", "form", "numeric"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "RangeSlider.jsx", path: "components/atoms/forms/RangeSlider.jsx" }],
    uses: ["Price range", "Volume control", "Rating", "Progress"],
    pageId: "rangeSlider",
  },
  {
    id: "date-input",
    name: "Date Input",
    slug: "date-input",
    category: "forms",
    description: "Native date picker with consistent styling across browsers.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["date", "input", "form", "picker"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "DateInput.jsx", path: "components/atoms/forms/DateInput.jsx" }],
    uses: ["Date of birth", "Booking dates", "Deadlines", "Scheduling"],
    pageId: "dateInput",
  },
  {
    id: "file-upload",
    name: "File Upload",
    slug: "file-upload",
    category: "forms",
    description: "Drag & drop file upload area with click-to-browse support.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["upload", "file", "form", "drag-drop"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "FileUpload.jsx", path: "components/atoms/forms/FileUpload.jsx" }],
    uses: ["Profile photo", "Document upload", "Attachments", "Media"],
    pageId: "fileUpload",
  },
  {
    id: "otp-input",
    name: "OTP Input",
    slug: "otp-input",
    category: "forms",
    description: "One-time password input with auto-focus between digits.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["otp", "pin", "input", "verification"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "OTPInput.jsx", path: "components/atoms/forms/OTPInput.jsx" }],
    uses: ["2FA verification", "Phone verification", "Email OTP", "PIN entry"],
    pageId: "otpInput",
  },
  {
    id: "input-label",
    name: "Input Label",
    slug: "input-label",
    category: "forms",
    description: "Accessible label with optional required asterisk indicator.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["label", "form", "accessibility"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "InputLabel.jsx", path: "components/atoms/forms/InputLabel.jsx" }],
    uses: ["Form labels", "Field descriptions", "Required indicators", "Accessibility"],
    pageId: "inputLabel",
  },
  {
    id: "input-error",
    name: "Input Error",
    slug: "input-error",
    category: "forms",
    description: "Animated error message for displaying validation feedback.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["error", "validation", "form", "feedback"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "InputError.jsx", path: "components/atoms/forms/InputError.jsx" }],
    uses: ["Validation errors", "Form feedback", "User guidance", "Error states"],
    pageId: "inputError",
  },
  {
    id: "helper-text",
    name: "Helper Text",
    slug: "helper-text",
    category: "forms",
    description: "Supplementary hint text to provide context or instructions.",
    framework: "react",
    language: "javascript",
    styling: "css",
    version: "1.0.0",
    dependencies: [],
    tags: ["hint", "helper", "form", "text"],
    author: "TemplateHub",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    files: [{ name: "HelperText.jsx", path: "components/atoms/forms/HelperText.jsx" }],
    uses: ["Field hints", "Character limits", "Format examples", "Guidance"],
    pageId: "helperText",
  },
];

export default formComponents;
